### ISSUE TITLE
Field value is removed when using Quick Edit

### ISSUE THREAD

**Issue by FaycalBoutam** [barn2plugins/easy-post-types-fields#13]
This is not specific to DLP, it will happen with any custom field and any post type.

> ======Full Description======
> DLP and EPT - When a document post is quick-edited, the custom field values created in EPT disappear. I didn't notice the same thing with custom fields created using ACF.
> 
> ======Steps to Replicate ======
> 1.) Install and activate DLP and EPT
> 2.) Create a text custom field and assign it to the DLP custom post type
> 3.) Create a DLP doc post and save a value in the custom field created above. Save.
> 4.) Go to the "all documents" list page and quick-edit the title of the document post created above. Save.
> 5.) Full-edit the said document post and check the custom field. You'll see that the value is gone.

If we bail [here](https://github.com/barn2plugins/easy-post-types-fields/blob/master/src/Post_Types/Abstract_Post_Type.php#L255) on the quick edit screen, it should fix the issue, ex:

```
if ( defined( 'DOING_AJAX' ) && DOING_AJAX && isset( $_POST['action'] ) && $_POST['action'] === 'inline-save' ) {
	return;
}
```

Ticket: @crispyliempo https://secure.helpscout.net/conversation/2419601421/96808?folderId=7603842

**Comment by amirition** [comment]
This is resolved in version 1.1.9.
