### ISSUE TITLE
"sort_by" attribute in PTP is not working when EPTF is active

### ISSUE THREAD

**Issue by FaycalBoutam** [barn2plugins/easy-post-types-fields#16]
@SandroSNunes already fixed this here https://github.com/barn2plugins/easy-post-types-fields/pull/15
Though I remember opening this somewhere, maybe it got lost with migration or something.

To reproduce, add this shortcode:
[posts_table_template id="3" sort_by="title" sort_order="asc"]
And you will see it's sorting by date, not title.

Ticket @adriannavajalevelup https://secure.helpscout.net/conversation/2634344641/112132/

**Comment by FaycalBoutam** [comment]
+1 @adriannavajalevelup https://secure.helpscout.net/conversation/2633951129/112109?viewId=7603842

**Comment by adriannavajalevelup** [comment]
@SandroSNunes Hey bro! Are there any updates on this? Thank you so much, bro! 😃

**Comment by amirition** [comment]
This has been resolved in version 1.1.10.

**Comment by adriannavajalevelup** [comment]
@amirition @FaycalBoutam The customer is happy and said thank you to the development team! 💯 🔥
